import { Inter } from "next/font/google";
import "./globals.css";
import Chatbot from "@/components/chatbot";
import { ClerkProvider } from "@clerk/nextjs";
import { neobrutalism } from '@clerk/themes'
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Brain Tumor detection",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClerkProvider
          appearance={{
            signIn: {
              baseTheme: [neobrutalism],
              variables: { colorPrimary: 'green' },
            },
            signUp: {
              baseTheme: [neobrutalism],
              variables: { colorPrimary: 'green' },
            },
          }}
        >
          {children}
          <Toaster/>
        </ClerkProvider>
        <div className="flex justify-end items-center">
          <Chatbot />
        </div>
      </body>
    </html>
  );
}
